baseurl = "http://sa.muel.be/"
languageCode = "en-us"
title = "Samuel Debruyn"
paginate = 9
theme = "crisp"

[params]
    twitter = "SamuelDebruyn"
    description = "personal website and blog of Samuel Debruyn"
    email = "s@muel.be"
    ga = "UA-51718684-1"
    hostname = "sa.muel.be"

[permalinks]
    post = "/:year/:title/"
    addendum = "/addendum/:year/:title/"

[author]
    name = "Samuel Debruyn"
    twitter = "SamuelDebruyn"
    email = "s@muel.be"
    birthDate = "1992-04-11"
    familyName = "Debruyn"
    givenName = "Samuel"
    nationality = "BE"
    gender = "male"