baseurl = "http://thuis.sa.muel.be:44888/"
languageCode = "en-us"
title = "Samuel Debruyn"
paginate = 8
theme = "crisp"
builddrafts = true

[params]
    twitter = "SamuelDebruyn"
    description = "personal website and blog of Samuel Debruyn"
    email = "s@muel.be"
    hostname = "sa.muel.be"

[permalinks]
    post = "/:year/:title/"
    addendum = "/addendum/:year/:title/"

[author]
    name = "Samuel Debruyn"
    email = "s@muel.be"
    birthDate = "1992-04-11"
    familyName = "Debruyn"
    givenName = "Samuel"
    nationality = "BE"
    gender = "male"