baseurl = "http://sa.muel.be/"
languageCode = "en-us"
title = "Samuel Debruyn"
paginate = 10
theme = "crisp"

[params]
    twitter = "SamuelDebruyn"
    description = "personal website and blog of Samuel Debruyn"
    ga = "UA-51718684-1"

[permalinks]
    post = "/:year/:title/"

[author]
    name = "Samuel Debruyn"